
const crimes = {
  "First-Degree Murder":       { min: 20, max: 40, capital: true,  definition: "Premeditated, intentional killing." },
  "Second-Degree Murder":      { min: 15, max: 30, capital: false, definition: "Intentional killing without premeditation." },
  "Voluntary Manslaughter":    { min: 3,  max: 10, capital: false, definition: "Killing in the heat of passion." },
  "Involuntary Manslaughter":  { min: 1,  max: 5,  capital: false, definition: "Unintentional killing due to recklessness or negligence." },
  "Aggravated Assault":        { min: 3,  max: 15, capital: false, definition: "Assault with a weapon or intent to cause serious harm." },
  "Simple Assault":            { min: 1,  max: 5,  capital: false, definition: "Threat or attempt to cause physical harm." },
  "Domestic Violence":         { min: 1,  max: 5,  capital: false, definition: "Violence against a partner or family member." },
  "Kidnapping":                { min: 10, max: 25, capital: false, definition: "Taking a person against their will." },
  "Rape":                      { min: 10, max: 30, capital: false, definition: "Non-consensual sexual intercourse." },
  "Aggravated Rape":           { min: 15, max: 40, capital: false, definition: "Rape involving violence, weapons, or minors." },
  "Armed Robbery":             { min: 7,  max: 20, capital: false, definition: "Robbery involving a weapon." },
  "Burglary":                  { min: 5,  max: 20, capital: false, definition: "Unlawful entry with intent to commit a crime." },
  "Arson":                     { min: 5,  max: 20, capital: false, definition: "Intentionally setting fire to property." },
  "Human Trafficking":         { min: 10, max: 30, capital: false, definition: "Exploitation of people through coercion or deception." },
  "Cannibalism":               { min: 15, max: 30, capital: false, definition: "Consumption of human flesh." },
  "Genocide":                  { min: 25, max: 50, capital: false, definition: "Systematic killing of a large group based on identity." },
  "Torture":                   { min: 5,  max: 25, capital: false, definition: "Infliction of severe pain for punishment or coercion." },
  "Drug Trafficking":          { min: 5,  max: 40, capital: false, definition: "Illegal distribution of drugs." },
  "Money Laundering":          { min: 5,  max: 20, capital: false, definition: "Concealing origins of illegally obtained money." },
  "Fraud":                     { min: 2,  max: 10, capital: false, definition: "Deceit for personal or financial gain." },
  "Embezzlement":              { min: 1,  max: 10, capital: false, definition: "Misappropriation of funds entrusted to someone." },
  "Bribery":                   { min: 1,  max: 5,  capital: false, definition: "Offering something of value to influence actions." },
  "Identity Theft":            { min: 2,  max: 20, capital: false, definition: "Stealing personal info for fraud." },
  "Cybercrime (Hacking)":      { min: 1,  max: 5,  capital: false, definition: "Unauthorized access to digital systems." },
  "Espionage":                 { min: 10, max: 30, capital: false, definition: "Spying on a government or organization." },
  "Terrorism":                 { min: 20, max: 50, capital: false, definition: "Violent acts to instill fear for political goals." },
  "Piracy":                    { min: 5,  max: 20, capital: false, definition: "Robbery or violence at sea." },
  "Hate Crime":                { min: 2,  max: 10, capital: false, definition: "Crime motivated by bias against identity." },
  "Other":                     { min: 0,  max: 0,  capital: false, definition: "Manually enter sentence length and capital status." }
};
